services:
  web:
    image: webdevops/php-apache-dev:7.3
    volumes:
      - "./src:/web"
    ports:
      - "8000:80"
    restart: always
    environment:
      - WEB_DOCUMENT_ROOT=/web/upload

  mysql:
    image: mysql:5.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=ocstore3
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
